### ISSUE TITLE
plugin submission

### ISSUE THREAD

**Issue by orthagh** [DebugBill/glpi2mdt#1]
Hello @DebugBill 

I just received you submission for this plugin on http://plugin.glpi-project.org.
At the moment, i can't accept it. You didn't released any archive of it and we can't accept empty plugins for referencing.
Please let me know (or resend your submission) when the plugin could be used.

If you want to advertise your work, please use social networks (we can relay) or mailing list of glpi.

Regards

**Comment by DebugBill** [comment]
Hi,

Thanks for your answer. I am really just starting and setting up the entire ecosystem for my plugin. I will resubmit as soon as there is some minimum code running

**Comment by orthagh** [comment]
Great ! Thank you

**Comment by DebugBill** [comment]
Hi,

I reopen this issue as there now is an archive available for version 0.0.1 of my plugin. Please let me know if you can accept it.

Yours,

Blaise

**Comment by orthagh** [comment]
Could you submit again the xml in the form: http://plugins.glpi-project.org/#/submit ?
i'll validate it immediatly

**Comment by DebugBill** [comment]
C’est fait

Blaise


De : Alexandre Delaunay [mailto:notifications@github.com]
Envoyé : mardi 5 septembre 2017 16:27
À : DebugBill/glpi2mdt
Cc : Blaise Thauvin; State change
Objet : Re: [DebugBill/glpi2mdt] plugin submission (#1)


Could you submit again the xml in the form: http://plugins.glpi-project.org/#/submit ?
i'll validate it immediatly
