### ISSUE TITLE
Modification en masse

### ISSUE THREAD

**Issue by Andromede88** [DebugBill/glpi2mdt#11]
Bonjour,

Le plugin fonctionne très bien sur mon infra, super boulot.

Je dois installé 100 machines et pour cela j'aimerais que toutes ces machines soit configurer sur la bonne séquence de taches.
Mais il n'est pas possible de sélectionner plusieurs machines et de sélectionner la séquence.
Dois je le faire directement en base ?

**Comment by DebugBill** [comment]
Merci, vous êtes le premier utilisateur à me dire que le plugin fonctionne chez lui :-)

Effectivement, si vous voulez faire un traitement en masse il sera plus simple de le faire en base, je n'ai prévu aucune fonction pour cela..
Sinon, vous pouvez peut être essayer d'utiliser les héritages de MDT lui même. De mémoire  (j'ai changé d'emploi et je n'utilise plus mon plugin ni MDT), il me semble que l'on peut mettre une séquence par défaut, soit dans le fichier ini soit dans l'arborescence. Celle que positionne le plugin est au niveau le plus fin, donc si on ne met rien dans GLPI celle par défaut devrait s'appliquer.

**Comment by Andromede88** [comment]
Merci pour l'info, j'ai modifier en base les différents éléments.
Mais je bloque sur un point, même si les éléments sont créer dans la base GLPI, le plugin ne créer pas d'entrée dans la base MDT sans obligatoirement faire un SAVE sur chaque machine.
J'ai regarder dans votre code mais n'étant pas développeur je suis vite perdu.
N'y aurait'il pas une commande ou un cron qui créer cela ?
