### ISSUE TITLE
Compatibility with GLPI 9.4.3 and PHP 7.2.24

### ISSUE THREAD

**Issue by pieterjanheyse** [DebugBill/glpi2mdt#14]
Hi, first of all thanks for making this piece of software. 
Could it be that it is not compatible with PHP 7.2.24? I am getting this error in my apache log upon installation: 

[Fri Nov 22 14:13:34.033915 2019] [php7:error] [pid 16720] [client 172.16.12.32:57628] PHP Fatal error:  Uncaught Error: Call to undefined function TableExists() in /mnt/nfs/web/glpi.scheppers-wetteren.be/plugins/glpi2mdt/hook.php:39\nStack trace:\n#0 /mnt/nfs/web/glpi.scheppers-wetteren.be/inc/plugin.class.php(521): plugin_glpi2mdt_install()\n#1 /mnt/nfs/web/glpi.scheppers-wetteren.be/front/plugin.form.php(47): Plugin->install('10')\n#2 {main}\n  thrown in /mnt/nfs/web/glpi.scheppers-wetteren.be/plugins/glpi2mdt/hook.php on line 39, referer: https://glpi.scheppers-wetteren.be/front/plugin.php

Can I help in any way to fix this?

**Comment by DebugBill** [comment]
Hi,

I would suspect it is not compatible with GLPI 9.4 even more than with PHP7.2 as this function is not part of PHP but comes from GLPI
Sadly I have moved to a new company that does not use GLPI and thus I have stopped developing the tool, and I am not in charge of local PCs in my new job. 
If you want to fix it I'll gladly accept the change requests you may send.

Blaise
