### ISSUE TITLE
Erreur lors de l'utilisation sous 9.5.5

### ISSUE THREAD

**Issue by cratedigger23** [DebugBill/glpi2mdt#18]
Bonjour,

Apres avoir bondit de joie en apprenant que ce plugin peux fonctionner sous GLPI 9.5.4 

J'ai voulut tenter l'aventure, en tentant d'installer le plugin une premiere fois tel quel sans success
Je suis parvenu a l'installer en modifiant les valeurs dans le fichier hook.php

!TableExists() par !$DB->TableExists() 

Le plugin est maintenant installer et activer, en revanche impossible d’accéder au parametres du plugins
http://glpi:8081/plugins/glpi2mdt/front/config.form.php

J'obtiens les messages suivant dans les logs php

[php_log.txt](https://github.com/DebugBill/glpi2mdt/files/6583206/php_log.txt)

Le dashboard affiche également comme quoi les tables ne sont pas au format InnoDB mais MyISAM

Je suis au courant que le plugin n'est plus maintenant, mais auriez vous une idée concernant ces problèmes pour faire fonctionner ce plugin avec les dernière version de GLPI ? (ce qui pourrait être une killer app si maintenu)

Windows server 2016, IIS 10
MariaDB
GLPI 9.5.5, PHP v8
php_odbc module installer
Plugin version 2.11

GLPI a été mis en place en version 9.5.2
il ne s'agit donc pas d'une migration

Bien cordialement,

Christophe

**Comment by DebugBill** [comment]
Pour information un utilisateur vient de m'envoyer un certain nombre de modifications visant à faire fonctionner le plugin sous GLPI 9.5 et PHP 7.3. Je viens de les intégrer. 
N'utilisant plus GLPI moi même je n'ai pas été en mesure de tester.

Cordialement
