### ISSUE TITLE
Compatibility version 10.0.X

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [DebugBill/glpi2mdt#21]
Hello, 
Do you have the ambition to make this plugin compatible with version 10.0.X?
Sincerely.

**Comment by DebugBill** [comment]
Hi,
I'm sorry but no. I developped this plugin years ago because I needed it. Since then I have moved to another company where I am not in charge of deployement and we don't use MDT.
But I will glady accept pull request if you happen to fix it.
