### ISSUE TITLE
Screen blank

### ISSUE THREAD

**Issue by ChristianFournier** [DebugBill/glpi2mdt#7]
The screen of glpi2mtd is totally blank.
The version of glpi is 9.24 and is on linux server (debian).

What  can be the problem and do you have a solution ?

Thanks !

**Comment by DebugBill** [comment]
Hi,

Just saw your question. I still run GLPI 9.1, so I guess GLPI2MDT might be incompatible with 9.2.4.  Did you check the PHP error log? There may be the answer there.

**Comment by ChristianFournier** [comment]
Hi 

Thanks for you email; 

Since i posted the message for the bug, we've migrated to glpi 9.3 but we have the same problem (blank screen) than before. 

Our php version is : PHP 5.6.33-0+deb8u1 

This is the error message in php logs 




[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBServer 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:93 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.027\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBPort 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:94 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBSchema 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:95 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBLogin 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:96 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBPassword 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:97 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: DBDriver 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:98 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 
[2018-09-17 14:16:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657 
*** PHP Notice(8): Undefined index: LatestVersion 
Backtrace : 
plugins/glpi2mdt/inc/mdt.class.php:102 
plugins/glpi2mdt/front/config.form.php:42 PluginGlpi2mdtMdt->__construct() 
{"user":"16@monserveur","mem_usage":"0.001\", 4.74Mio)"} 

If you have a solution ? 

Sincerely, 

Christian FOURNIER 
Assistant Informatique et Audiovisuel 
2 rue Louise et Victor Champier 
BP 30329 - 59056 Roubaix Cedex 1 
Tel: +33 (0)3 20 25 89 95 
christian.fournier@ensait.fr 
www.ensait.fr 




----- Mail original -----

De: "Blaise Thauvin" <notifications@github.com> 
À: "DebugBill/glpi2mdt" <glpi2mdt@noreply.github.com> 
Cc: "ChristianFournier" <christian.fournier@ensait.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 15 Septembre 2018 21:57:56 
Objet: Re: [DebugBill/glpi2mdt] Screen blank (#7) 



Hi, 

Just saw your question. I still run GLPI 9.1, so I guess GLPI2MDT might be incompatible with 9.2.4. Did you check the PHP error log? There may be the answer there.

**Comment by DebugBill** [comment]
I suspect you did not go to the configuration page for the module first. Hence there is no data to fill the variable DBServer

**Comment by DebugBill** [comment]
No answer. Guess problem solved

**Comment by DebugBill** [comment]
No answer. Guess problem solved
