### ISSUE TITLE
Configuration du plugin

### ISSUE THREAD

**Issue by Skryz974** [DebugBill/glpi2mdt#9]
Bonjour,

Sorry, I don't speak English. 
If necessary I will post the ticket again tethering google translation

Ma config
SRV001 : MDT et SQL Server
SRV002 : WampServer et GLPI

Dans mon cas de figure comment doit-on procéder pour la configuration du plugin.
- Que doit-on faire sur SRV001 et SRV002? Faut-il installer le ODBC Driver 13 for SQL Server sur un des deux serveurs(ou les deux) et configurer un nouvelle source de données(utilisateurs?! système?!)
- Le chemin vers le dossier "control" doit être sous la forme "\\serveur-mdt\DeploymentShare$\control" ?
- Le nom DNS du Serveur SQL doit-il contenir le nom de l'instance(SRV001 ou SRV001\MDT)

Merci par avance pour votre aide.

**Comment by DebugBill** [comment]
Bonjour

Je ne sais pas si GLPI2MDT fonctionne sous Windows. Je l'ai développé sur un serveur Linux. Il y a surement moyen de le faire fonctionner mais surement avec quelques évolutions.

l'ODBC doit être installé sur le serveur GLPI, pour se connecter à la base MS-SQL sur le serveur MDT. Sous linux on ne configure pas de source de donnée. Elle est définie dans le paramétrage du module GLPI2MDT
Je ne sais pas si un chemin en \\serveur\repertoire peut fonctionner. Là encore sous linux il s'agit d'un point de montage, et donc d'un chemin local (l'équivalent en Windows serait du genre "E:\repertoire\". PHP s'appuie sur des librairies qui sont peut être capables d'interpréter un chemin windows. Il faut tester.

Le nom DNS est bien un nom DNS, pas un chemin. C'est donc de la forme serveur.domain.extension, ou simplement "serveur" si le domaine est implicite (mais ce n'est pas une configuration propre.

En conclusion, il faut tester, regarder dans les logs ce qui plante, et peut être constater qu'il faut modifier légèrement le code pour faire fonctionner sous windows. Ceci dit, cela peut être l'occasion de contribuer à une évolution du code :-)

**Comment by DebugBill** [comment]
No answer. Guess problem solved
